import{a as h,S as L,i as u}from"./assets/vendor-DQvd0HNi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();async function f(o,t){let r=15;h.defaults.baseURL="https://pixabay.com";const l=new URLSearchParams({key:"55116148-63b4b48da282efb6025f7a072",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:r}),e=await h.get(`/api/?${l}`);return console.log(e),e.data}let b=new L(".img-link");function m(o){const t=o.map(r=>`<div class="gallery-item">
        <a class="img-link" href="${r.largeImageURL}"><img class="img" src="${r.webformatURL}" alt="${r.tags}" width='360' height='156'>
        <ul class="img-descr">
    <li class="descr"><h2 class="title-descr">Likes</h2>  <p class="descr-text">${r.likes}</p></li>
      <li class="descr"><h2 class="title-descr">Views</h2>  <p class="descr-text">${r.views}</p></li>
      <li class="descr"><h2 class="title-descr">Comments</h2>  <p class="descr-text">${r.comments}</p></li>
      <li class="descr"><h2 class="title-descr">Downloads</h2> <p class="descr-text">${r.downloads}</p></li></ul>
    </ul></a>
        
    </div>`).join("");a.galleryEl.insertAdjacentHTML("beforeend",t),b.refresh()}function w(){return a.galleryEl.innerHTML=""}function g(){return a.loader.classList.add("loader")}function d(){return a.loader.classList.remove("loader")}function S(){return a.fetchButton.classList.remove("disabled")}function y(){return a.fetchButton.classList.add("disabled")}const a={formEl:document.querySelector(".form"),inputEl:document.querySelector('input[name="search-text"]'),searchButtonEl:document.querySelector("button"),galleryEl:document.querySelector(".gallery"),loader:document.querySelector(".js-loader"),fetchButton:document.querySelector(".fetch-button")};let p=15,c=1,n;a.formEl.addEventListener("submit",v);a.fetchButton.addEventListener("click",q);async function v(o){if(o.preventDefault(),w(),n=a.inputEl.value.trim(),n===""){u.show({color:"red",message:"Sorry, there are no images matching your search query. Please try again!"});return}g();try{const t=await f(n,c);if(t.length===0){u.show({color:"red",message:"Sorry, there are no images matching your search query. Please try again!"}),d();return}d(),m(t.hits);const r=t.totalHits/p;c>r&&y(),S()}catch(t){console.log(t)}}async function q(){console.log("click"),c+=1,g();try{const o=await f(n,c);d(),m(o.hits);const t=document.querySelector(".gallery-item");console.log(t.getBoundingClientRect());const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"});const l=o.totalHits/p;console.log(l),c>l&&(y(),u.show({color:"red",message:"We're sorry, but you've reached the end of search results."}))}catch(o){console.log(o)}}
//# sourceMappingURL=index.js.map
