import{a as f,S as L,i as u}from"./assets/vendor-DQvd0HNi.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();async function m(s,e){let r=15;f.defaults.baseURL="https://pixabay.com";const l=new URLSearchParams({key:"55116148-63b4b48da282efb6025f7a072",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:r});return(await f.get(`/api/?${l}`)).data}let b=new L(".img-link");function g(s){const e=s.map(r=>`<div class="gallery-item">
        <a class="img-link" href="${r.largeImageURL}"><img class="img" src="${r.webformatURL}" alt="${r.tags}" width='360' height='156'>
        <ul class="img-descr">
    <li class="descr"><h2 class="title-descr">Likes</h2>  <p class="descr-text">${r.likes}</p></li>
      <li class="descr"><h2 class="title-descr">Views</h2>  <p class="descr-text">${r.views}</p></li>
      <li class="descr"><h2 class="title-descr">Comments</h2>  <p class="descr-text">${r.comments}</p></li>
      <li class="descr"><h2 class="title-descr">Downloads</h2> <p class="descr-text">${r.downloads}</p></li></ul>
    </ul></a>
        
    </div>`).join("");a.galleryEl.insertAdjacentHTML("beforeend",e),b.refresh()}function w(){return a.galleryEl.innerHTML=""}function y(){return a.loader.classList.add("loader")}function d(){return a.loader.classList.remove("loader")}function S(){return a.fetchButton.classList.remove("disabled")}function h(){return a.fetchButton.classList.add("disabled")}const a={formEl:document.querySelector(".form"),inputEl:document.querySelector('input[name="search-text"]'),searchButtonEl:document.querySelector("button"),galleryEl:document.querySelector(".gallery"),loader:document.querySelector(".js-loader"),fetchButton:document.querySelector(".fetch-button")};let p=15,c=1,n;a.formEl.addEventListener("submit",v);a.fetchButton.addEventListener("click",q);async function v(s){if(s.preventDefault(),w(),c=1,n=a.inputEl.value.trim(),n===""){u.show({color:"red",message:"Sorry, there are no images matching your search query. Please try again!"});return}y();try{const e=await m(n,c);if(e.length===0){h(),u.show({color:"red",message:"Sorry, there are no images matching your search query. Please try again!"}),d();return}d(),g(e.hits);const r=e.totalHits/p;c>r&&h(),S()}catch(e){console.log(e)}}async function q(){console.log("click"),c+=1,y();try{const s=await m(n,c);d(),g(s.hits);const e=document.querySelector(".gallery-item");console.log(e.getBoundingClientRect());const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"});const l=s.totalHits/p;c>l&&(h(),u.show({color:"red",message:"We're sorry, but you've reached the end of search results."}))}catch(s){console.log(s)}}
//# sourceMappingURL=index.js.map
