import{a as f,S as w,i}from"./assets/vendor-DQvd0HNi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const h of s.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&n(h)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();async function m(o,t){let r=15;f.defaults.baseURL="https://pixabay.com";const n=new URLSearchParams({key:"55116148-63b4b48da282efb6025f7a072",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:r});return(await f.get(`/api/?${n}`)).data}let b=new w(".img-link");function g(o){const t=o.map(r=>`<div class="gallery-item">
        <a class="img-link" href="${r.largeImageURL}"><img class="img" src="${r.webformatURL}" alt="${r.tags}" width='360' height='156'>
        <ul class="img-descr">
    <li class="descr"><h2 class="title-descr">Likes</h2>  <p class="descr-text">${r.likes}</p></li>
      <li class="descr"><h2 class="title-descr">Views</h2>  <p class="descr-text">${r.views}</p></li>
      <li class="descr"><h2 class="title-descr">Comments</h2>  <p class="descr-text">${r.comments}</p></li>
      <li class="descr"><h2 class="title-descr">Downloads</h2> <p class="descr-text">${r.downloads}</p></li></ul>
    </ul></a>
        
    </div>`).join("");a.galleryEl.insertAdjacentHTML("beforeend",t),b.refresh()}function v(){return a.galleryEl.innerHTML=""}function y(){return a.loader.classList.add("loader")}function l(){return a.loader.classList.remove("loader")}function p(){return a.fetchButton.classList.remove("disabled")}function c(){return a.fetchButton.classList.add("disabled")}const a={formEl:document.querySelector(".form"),inputEl:document.querySelector('input[name="search-text"]'),searchButtonEl:document.querySelector("button"),galleryEl:document.querySelector(".gallery"),loader:document.querySelector(".js-loader"),fetchButton:document.querySelector(".fetch-button")};let L=15,u=1,d;a.formEl.addEventListener("submit",S);a.fetchButton.addEventListener("click",E);async function S(o){if(o.preventDefault(),c(),v(),u=1,d=a.inputEl.value.trim(),d===""){l(),i.show({color:"red",message:"Sorry, there are no images matching your search query. Please try again!"});return}y();try{const t=await m(d,u);if(t.hits.length===0){c(),i.show({color:"red",message:"Sorry, there are no images matching your search query. Please try again!"}),l();return}l(),g(t.hits),p();const r=Math.ceil(t.totalHits/L);u>=r&&(l(),c(),i.show({color:"red",message:"We're sorry, but you've reached the end of search results."}))}catch{l(),c(),i.show({color:"red",message:"ERROR!"})}}async function E(){c(),u+=1,y();try{const o=await m(d,u);l(),g(o.hits);const t=document.querySelector(".gallery-item");console.log(t.getBoundingClientRect());const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"}),p();const n=Math.ceil(o.totalHits/L);u>=n&&(l(),c(),i.show({color:"red",message:"We're sorry, but you've reached the end of search results."}))}catch{l(),c(),i.show({color:"red",message:"ERROR!"})}}
//# sourceMappingURL=index.js.map
